# Generated by Django 4.1.5 on 2023-06-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=122)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('address', models.CharField(max_length=200)),
                ('streetaddress', models.CharField(max_length=122)),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=100)),
                ('abc', models.CharField(max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('residential', models.CharField(default='', max_length=100)),
                ('ybd', models.DateField(default=None, verbose_name=-19800)),
                ('dop', models.DateField(default=None, verbose_name=-19800)),
                ('famt', models.TextField(default='')),
                ('asf', models.TextField(default='')),
                ('loan', models.TextField(default='')),
                ('desc', models.TextField(default='')),
            ],
        ),
    ]
